### PR TITLE
fix compilation error caused due to ticker missing brackets !

### PR DESCRIPTION
**Pull request by Abhinavgupta371**
Change-Id: I42e13d4da93fa23def76b520f702d48d3fe5f00a

### CODE REVIEW

**Review by Klozz — APPROVED** [review]

**Comment by Klozz** [comment]
Thanks I forget to upload the commit fixed I had it locally

**Comment by Abhinavgupta371** [comment]
No problem sir 😅

**Comment by Abhinavgupta371** [comment]
Should i close this or you gonna merge it? 😅

**Comment by Klozz** [comment]
Its merged now :P

**Pull request merged**
